-- Approved Alumdoor local pricing surcharge seed. Safe to rerun.

INSERT INTO documents(tenant_id,doc_key,doctype,name,owner,docstatus,status,version,created_at,modified_at,payload_json,modified_by)
VALUES('demo','Pricing Scope:CỬA ÁP DỤNG SƠN VÂN GỖ','Pricing Scope','CỬA ÁP DỤNG SƠN VÂN GỖ','codex-local',0,'Draft',1,'2026-08-12T03:20:52.791Z','2026-08-12T03:20:52.791Z',json('{"scope_name":"CỬA ÁP DỤNG SƠN VÂN GỖ","members":[{"member_type":"Item Group","item_group":"Cửa CN Đức"},{"member_type":"Item Group","item_group":"Cửa tấm liền Úc"},{"member_type":"Item Group","item_group":"Cửa siêu trường"},{"member_type":"Item Group","item_group":"Cửa Đài Loan"}],"disabled":false,"_metadata_revision":1}'),'codex-local')
ON CONFLICT(tenant_id,doc_key) DO UPDATE SET payload_json=excluded.payload_json,version=documents.version+1,modified_at=excluded.modified_at,modified_by=excluded.modified_by;

INSERT INTO documents(tenant_id,doc_key,doctype,name,owner,docstatus,status,version,created_at,modified_at,payload_json,modified_by)
VALUES('demo','Pricing Scope:RAY TD ÁP DỤNG PHỤ THU SƠN','Pricing Scope','RAY TD ÁP DỤNG PHỤ THU SƠN','codex-local',0,'Draft',1,'2026-08-12T03:20:52.791Z','2026-08-12T03:20:52.791Z',json('{"scope_name":"RAY TD ÁP DỤNG PHỤ THU SƠN","members":[{"member_type":"Item","item_code":"TP-RAYHOP"},{"member_type":"Item","item_code":"TP-RAY HỘP TD U100"},{"member_type":"Item","item_code":"TP-TD87A1 GS"},{"member_type":"Item","item_code":"NVL-TOLE1.2x190-KRON"}],"disabled":false,"_metadata_revision":1}'),'codex-local')
ON CONFLICT(tenant_id,doc_key) DO UPDATE SET payload_json=excluded.payload_json,version=documents.version+1,modified_at=excluded.modified_at,modified_by=excluded.modified_by;

INSERT INTO documents(tenant_id,doc_key,doctype,name,owner,docstatus,status,version,created_at,modified_at,payload_json,modified_by)
VALUES('demo','Pricing Scope:V4 V5 SƠN TĨNH ĐIỆN','Pricing Scope','V4 V5 SƠN TĨNH ĐIỆN','codex-local',0,'Draft',1,'2026-08-12T03:20:52.791Z','2026-08-12T03:20:52.791Z',json('{"scope_name":"V4 V5 SƠN TĨNH ĐIỆN","members":[{"member_type":"Item","item_code":"NVL-V4_KEM_STD"},{"member_type":"Item","item_code":"NVL-V5_KEM_STD-02"}],"disabled":false,"_metadata_revision":1}'),'codex-local')
ON CONFLICT(tenant_id,doc_key) DO UPDATE SET payload_json=excluded.payload_json,version=documents.version+1,modified_at=excluded.modified_at,modified_by=excluded.modified_by;

INSERT INTO documents(tenant_id,doc_key,doctype,name,owner,docstatus,status,version,created_at,modified_at,payload_json,modified_by)
VALUES('demo','Item Color:VÂN GỖ','Item Color','VÂN GỖ','codex-local',0,'Draft',1,'2026-08-12T03:20:52.791Z','2026-08-12T03:20:52.791Z',json('{"color_code":"VÂN GỖ","color_name":"VÂN GỖ","finish":"Sơn vân gỗ","applies_to_groups":[{"row_id":"SCOPE-01","item_group":"Cửa CN Đức"},{"row_id":"SCOPE-02","item_group":"Cửa tấm liền Úc"},{"row_id":"SCOPE-03","item_group":"Cửa siêu trường"},{"row_id":"SCOPE-04","item_group":"Cửa Đài Loan"}],"note":"Màu/bề mặt dùng để tính phụ thu sơn vân gỗ.","disabled":false,"usage_scope":"Mua & bán","_metadata_revision":2}'),'codex-local')
ON CONFLICT(tenant_id,doc_key) DO UPDATE SET payload_json=excluded.payload_json,version=documents.version+1,modified_at=excluded.modified_at,modified_by=excluded.modified_by;

INSERT INTO documents(tenant_id,doc_key,doctype,name,owner,docstatus,status,version,created_at,modified_at,payload_json,modified_by)
VALUES('demo','Pricing Rule:PHỤ THU SƠN VÂN GỖ CỬA','Pricing Rule','PHỤ THU SƠN VÂN GỖ CỬA','codex-local',0,'Draft',1,'2026-08-12T03:20:52.791Z','2026-08-12T03:20:52.791Z',json('{"title":"Phụ thu sơn vân gỗ cửa +465.000/m²","effect_type":"ADJUSTMENT","price_list":"Bảng giá 31/07/2026","pricing_scope":"CỬA ÁP DỤNG SƠN VÂN GỖ","adjustment_basis":"AREA_SQM","adjustment_rate":465000,"priority":100,"conditions":[{"field":"color","operator":"eq","value":"VÂN GỖ"}],"taxable":true,"discountable":false,"disabled":false,"_metadata_revision":28}'),'codex-local')
ON CONFLICT(tenant_id,doc_key) DO UPDATE SET payload_json=excluded.payload_json,version=documents.version+1,modified_at=excluded.modified_at,modified_by=excluded.modified_by;

INSERT INTO documents(tenant_id,doc_key,doctype,name,owner,docstatus,status,version,created_at,modified_at,payload_json,modified_by)
VALUES('demo','Pricing Rule:PHỤ THU RAY VÂN GỖ','Pricing Rule','PHỤ THU RAY VÂN GỖ','codex-local',0,'Draft',1,'2026-08-12T03:20:52.791Z','2026-08-12T03:20:52.791Z',json('{"title":"Phụ thu ray sơn vân gỗ +55.000/m","effect_type":"ADJUSTMENT","price_list":"Bảng giá 31/07/2026","pricing_scope":"RAY TD ÁP DỤNG PHỤ THU SƠN","adjustment_basis":"LENGTH_M","adjustment_rate":55000,"priority":110,"exclusive_group":"MÀU RAY","conditions":[{"field":"color","operator":"eq","value":"VÂN GỖ"}],"taxable":true,"discountable":false,"disabled":false,"_metadata_revision":28}'),'codex-local')
ON CONFLICT(tenant_id,doc_key) DO UPDATE SET payload_json=excluded.payload_json,version=documents.version+1,modified_at=excluded.modified_at,modified_by=excluded.modified_by;

INSERT INTO documents(tenant_id,doc_key,doctype,name,owner,docstatus,status,version,created_at,modified_at,payload_json,modified_by)
VALUES('demo','Pricing Rule:PHỤ THU RAY MÀU KHÁC','Pricing Rule','PHỤ THU RAY MÀU KHÁC','codex-local',0,'Draft',1,'2026-08-12T03:20:52.791Z','2026-08-12T03:20:52.791Z',json('{"title":"Phụ thu ray màu khác +15.000/m","effect_type":"ADJUSTMENT","price_list":"Bảng giá 31/07/2026","pricing_scope":"RAY TD ÁP DỤNG PHỤ THU SƠN","adjustment_basis":"LENGTH_M","adjustment_rate":15000,"priority":100,"exclusive_group":"MÀU RAY","conditions":[{"field":"color","operator":"neq","value":""},{"field":"color","operator":"neq","value":"VÀNG KEM"},{"field":"color","operator":"neq","value":"GHI SẦN"},{"field":"color","operator":"neq","value":"VÂN GỖ"}],"taxable":true,"discountable":false,"disabled":false,"_metadata_revision":28}'),'codex-local')
ON CONFLICT(tenant_id,doc_key) DO UPDATE SET payload_json=excluded.payload_json,version=documents.version+1,modified_at=excluded.modified_at,modified_by=excluded.modified_by;

INSERT INTO documents(tenant_id,doc_key,doctype,name,owner,docstatus,status,version,created_at,modified_at,payload_json,modified_by)
VALUES('demo','Pricing Rule:PHỤ THU V4 V5 SƠN TĨNH ĐIỆN','Pricing Rule','PHỤ THU V4 V5 SƠN TĨNH ĐIỆN','codex-local',0,'Draft',1,'2026-08-12T03:20:52.791Z','2026-08-12T03:20:52.791Z',json('{"title":"Phụ thu V4/V5 sơn tĩnh điện +15.000/m","effect_type":"ADJUSTMENT","price_list":"Bảng giá 31/07/2026","pricing_scope":"V4 V5 SƠN TĨNH ĐIỆN","adjustment_basis":"LENGTH_M","adjustment_rate":15000,"priority":100,"taxable":true,"discountable":false,"disabled":false,"_metadata_revision":28}'),'codex-local')
ON CONFLICT(tenant_id,doc_key) DO UPDATE SET payload_json=excluded.payload_json,version=documents.version+1,modified_at=excluded.modified_at,modified_by=excluded.modified_by;
