import type { DocField, DocTypeMeta, DocTypeView } from "@metaforge/core";

function isLayout(fieldtype: string): boolean {
  return [
    "Section Break", "Column Break", "Tab Break", "Fold", "Heading", "HTML", "Button",
    "Table", "Table MultiSelect",
  ].includes(fieldtype);
}

function declaredFields(view: DocTypeView | undefined): string[] {
  const values = view?.columns?.length ? view.columns : view?.fields;
  return Array.isArray(values)
    ? values.map((value) => String(value ?? "").trim()).filter(Boolean)
    : [];
}

function fieldMap(meta: DocTypeMeta): Map<string, DocField> {
  return new Map((meta.fields ?? []).map((field) => [field.fieldname, field]));
}

function isRenderableField(field: DocField | undefined): field is DocField {
  return field !== undefined && !isLayout(field.fieldtype);
}

function orderedFields(meta: DocTypeMeta, names: readonly string[]): DocField[] {
  const byName = fieldMap(meta);
  return names
    .map((name) => byName.get(name))
    .filter(isRenderableField);
}

/**
 * Surface that the brief compiler derives when an app author did not make a presentation choice.
 * Keeping this mirror small lets the table runtime distinguish an explicit migration from the
 * compiler's safe defaults; otherwise every existing child table would silently switch renderers.
 */
function derivedDefaultSurface(field: DocField): "quick" | "expanded" | "internal" {
  if (field.hidden === 1 || field.editMode === "hidden" || isLayout(field.fieldtype)) return "internal";
  if (field.reqd === 1 && field.editMode !== "readonly") return "quick";
  return "expanded";
}

function hasExplicitSurfaceOverride(meta: DocTypeMeta): boolean {
  return (meta.fields ?? []).some((field) =>
    field.surface != null && field.surface !== derivedDefaultSurface(field));
}

/**
 * Metadata-only presentation contract for a child table.
 *
 * `form.columns` (or `form.fields`) is the full spreadsheet/detail order.
 * `quickEntry.columns` is the compact order shown in the parent document.
 * `surface=internal` never renders as a business column; `surface=expanded` is available
 * in the full sheet/detail surface but does not clutter the compact entry surface.
 *
 * The resolver deliberately knows nothing about any particular DocType or vertical.
 */
export function metadataChildGridColumns(
  meta: DocTypeMeta,
  expanded: boolean,
): DocField[] | null {
  if (!hasMetadataChildGridPresentation(meta)) return null;

  const fullNames = declaredFields(meta.viewPolicy?.form);
  const compactNames = declaredFields(meta.viewPolicy?.quickEntry);
  const explicitNames = expanded
    ? fullNames
    : compactNames.length ? compactNames : fullNames;

  if (explicitNames.length) {
    return orderedFields(meta, explicitNames).filter((field) => field.surface !== "internal");
  }

  const fields = (meta.fields ?? []).filter((field) => !isLayout(field.fieldtype) && field.surface !== "internal");
  return fields.filter((field) => expanded
    ? field.surface === "quick" || field.surface === "expanded" || field.surface == null
    : field.surface === "quick" || field.surface == null);
}

/**
 * Returns compact-hidden columns only when metadata explicitly owns the grid policy.
 * `null` means the caller may use a legacy fallback during migration; an empty array means
 * metadata explicitly says that no displayed column is hidden.
 */
export function metadataChildGridHiddenColumns(
  meta: DocTypeMeta,
  columns: readonly DocField[],
  expanded: boolean,
): string[] | null {
  if (!hasMetadataChildGridPresentation(meta)) return null;
  if (expanded) return [];

  const compactNames = declaredFields(meta.viewPolicy?.quickEntry);
  if (compactNames.length) {
    const compact = new Set(compactNames);
    return columns.filter((field) => !compact.has(field.fieldname)).map((field) => field.fieldname);
  }

  return columns
    .filter((field) => field.surface === "expanded" || field.surface === "internal")
    .map((field) => field.fieldname);
}

/**
 * True only when metadata explicitly opts into ownership.
 *
 * Child-table `form`/`quickEntry` policies generated by the base brief compiler are disabled and
 * carry safe defaults for every app. They must not, by themselves, switch a mature table to a new
 * renderer. An enabled authored view or any surface that differs from the compiler default is an
 * explicit opt-in and is safe to route through MetadataChildGrid.
 */
export function hasMetadataChildGridPresentation(meta: DocTypeMeta): boolean {
  const authoredView = Boolean(
    (meta.viewPolicy?.form?.enabled && declaredFields(meta.viewPolicy.form).length > 0)
    || (meta.viewPolicy?.quickEntry?.enabled && declaredFields(meta.viewPolicy.quickEntry).length > 0),
  );
  return authoredView || hasExplicitSurfaceOverride(meta);
}
